### PR TITLE
Fix for Issue #126 and #125

### LINKED ISSUE #126: GCM Adapter misspelled parameters leading to wrong behavior
The GCM Adapter uses from line 125 until 129 camelCased parameter names but defines them in `getDefinedParameters` in snakeCase.

this results in Erros if you pass the params into construct in camelCase.
if you pass them as defined in snakeCase the ServiceMessage is constructed without those keys

### PR DESCRIPTION
**Pull request by theluk**
fixes #126 and #125 

fixing naming from snake case to camel case

### CODE REVIEW

**Comment by seyfer** [comment]
@theluk, good job. You have even taken care about docs. :+1: 

I have only one error on php 7.1 with atoum tests:

```
Failure (9 tests, 32/32 methods, 0 void method, 0 skipped method, 0 uncompleted method, 0 failure, 2 errors, 0 exception)!
> There are 2 errors:
=> tests\units\Sly\NotificationPusher\Adapter\Gcm::testPush():
==> Error E_WARNING in /home/seyfer/www/NotificationPusher/tests/units/Sly/NotificationPusher/Adapter/Gcm.php on line 169, generated by file /home/seyfer/www/NotificationPusher/src/Sly/NotificationPusher/Adapter/Gcm.php on line 82:
array_diff_key(): Argument #1 is not an array
==> Error E_WARNING in /home/seyfer/www/NotificationPusher/tests/units/Sly/NotificationPusher/Adapter/Gcm.php on line 169, generated by file /home/seyfer/www/NotificationPusher/src/Sly/NotificationPusher/Adapter/Gcm.php on line 82:
array_merge(): Argument #2 is not an array
```

Could you please check it with php 7.1 ?
Please, don't use `@` to suppress warnings, it's a bad practice. It's better to fix the code to not produce any warnings.

File: src/Sly/NotificationPusher/Adapter/Gcm.php [hunk 1]
```diff
@@ -138,11 +138,11 @@ public function getServiceMessageFromOrigin(array $tokens, BaseOptionedModel $me
     public function getDefinedParameters()
     {
         return [
-            'collapse_key',
```
Comment (seyfer) [inline src/Sly/NotificationPusher/Adapter/Gcm.php]: @theluk, are you sure here? Please check https://github.com/Ph3nol/NotificationPusher/issues/144
Also, we had another 2 issues where people proposed to do opposite renaming from camelCase to under_score.

File: src/Sly/NotificationPusher/Adapter/Gcm.php [hunk 2]
```diff
@@ -67,15 +67,25 @@ public function push(PushInterface $push)
...
+                $response = $client->send($message);
+                $responseResults = $response->getResults();
+
+                if ((bool) $response->getSuccessCount()) {
+                    foreach ($tokensRange as $token) {
+                        $device = $push->getDevices()->get($token);
+                        
+                        // map the overall response object
+                        // into a per device response
+                        $tokenResponse = @$responseResults[$token] ?: [];
```
Comment (seyfer) [inline src/Sly/NotificationPusher/Adapter/Gcm.php]: @theluk, it's not a good idea to use `@` to suppress warnings. Is there another way to check errors?

File: src/Sly/NotificationPusher/Adapter/Gcm.php [hunk 3]
```diff
@@ -71,21 +71,19 @@ public function push(PushInterface $push)
...
-                        $push->addResponse($device, $tokenResponse);
-                        
-                        $pushedDevices->add($device);
-                    }
+                foreach ($tokensRange as $token) {
+                    $device = $push->getDevices()->get($token);
+                    
+                    // map the overall response object
+                    // into a per device response
+                    $tokenResponse = @$responseResults[$token] ?: [];
```
Comment (seyfer) [inline src/Sly/NotificationPusher/Adapter/Gcm.php]: @theluk, it's not a good idea to use `@` to suppress warnings. Is there another way to check errors?

File: src/Sly/NotificationPusher/Adapter/Gcm.php [hunk 4]
```diff
@@ -71,21 +71,19 @@ public function push(PushInterface $push)
...
+                    $tokenResponse = array_merge(
+                        $tokenResponse, 
+                        array_diff_key($response->getResponse(), ['results' => true])
```
Comment (seyfer) [inline src/Sly/NotificationPusher/Adapter/Gcm.php]: @theluk, atoum test failing here on php 7.1. Please, check https://github.com/Ph3nol/NotificationPusher/pull/127#issuecomment-318909487

File: src/Sly/NotificationPusher/Adapter/Gcm.php (hunk 1 above)
Comment (seyfer) [inline src/Sly/NotificationPusher/Adapter/Gcm.php]: @theluk, now I have examined the code and I see, that you made parameter names all in camel case everywhere. Now they are consistent and it's ok. :+1:

File: src/Sly/NotificationPusher/Adapter/Gcm.php (hunk 4 above)
Comment (theluk) [inline src/Sly/NotificationPusher/Adapter/Gcm.php]: it seems that it fails because the `getResponse` from the mocked client does not return an array.
But as of zendframework\zendservice-google-gcm\library\ZendService\Google\Gcm\Client.php the response is always given, otherwise an exception is thrown.

**Comment by seyfer** [comment]
@theluk, now tests passing, thank you. Will merge soon.
