### PR TITLE
157 fix

### LINKED ISSUE #157: GCM Adapter bug
With the new 2.3.2 library version you change GCMAdapter line 148 from 
`$serviceMessage->setData($data);`
to
`$serviceMessage->setNotification($data);`

but this is not generally correct because **Data Message** an **Notification Message** are quite different in android application (Google official documentation:
https://firebase.google.com/docs/cloud-messaging/concept-options)

Actually we rollbak to 2.3.1 release to fix this problem.
Can you restore old code or otherwise offer a setter methods to support both android notification mode?

### PR DESCRIPTION
**Pull request by seyfer**
#157 fix

### CODE REVIEW

File: src/Sly/NotificationPusher/Model/GcmMessage.php [hunk 1]
```diff
@@ -0,0 +1,28 @@
+<?php
+
+namespace Sly\NotificationPusher\Model;
+
+
+class GcmMessage extends Message
+{
+    /**
```
Comment (morloderex) [inline src/Sly/NotificationPusher/Model/GcmMessage.php]: I think we need to have the ability to set the data key here as well otherwise this is not that useful.

Comment (seyfer) [reply src/Sly/NotificationPusher/Model/GcmMessage.php]: @morloderex hey, it extends Message. So you could use it like a regular Message with data or set some notificationData in addition.

Comment (morloderex) [reply src/Sly/NotificationPusher/Model/GcmMessage.php]: Yeah but having both in the same class makes a lot of sense to me.

Comment (seyfer) [reply src/Sly/NotificationPusher/Model/GcmMessage.php]: @morloderex personally I agree, that having `private $data;`
would be better
just because in the core design Message class initially use arrays, so it would require more changes and BC or support both ways.
what if a user set data via field and via array param, then they need to be merged. but in which order? not trivial.

Comment (seyfer) [reply src/Sly/NotificationPusher/Model/GcmMessage.php]: better add as separated PR
